server:
  port: 80
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123123
      url: jdbc:mysql://localhost:3306/reggie?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
  #配置redis
  redis:
    port: 6379
    host: 127.0.0.1
    database: 1
  cache:
    type: redis #设置缓存类型为redis
    redis:
      time-to-live: 1800000  #设置缓存时间 单位毫秒

mybatis:
  configuration:
    #开启mybatis日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #开启实体类的简称
  type-aliases-package: com.qiansheng.reggie.pojo
  #配置mybatis配置文件xml的位置
  config-locations: classpath:com/qiansheng/reggie/mapper/*.xml
mydate:
  imgPath: E:\瑞吉外卖-资料\1 瑞吉外卖项目\1 瑞吉外卖项目\资料\图片资源\
SMSInf:
  accessKeyId: dddddd
  accessKeySecret: aaaaa
  TemplateCode: SMS_221056574
  SignName: 软考助手